#spring:
#  datasource:
#    url: jdbc:p6spy:postgresql://localhost:5432/demo
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: stoneberg
#    password: new1234@
#
#    hikari:
#      connection-timeout: 30000
#      minimum-idle: 3
#      maximum-pool-size: 5
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate.ddl-auto: update
#    properties:
#      hibernate.default_batch_fetch_size: 500
#      hibernate.jdbc.lob.non_contextual_creation: true

##### for H2 Database
spring:
  datasource:
    url: jdbc:p6spy:h2:mem:testdb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500

