server:
  port: 8080

#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

logging:
  config: classpath:logback/logback-spring.xml
        
spring:
  # Default Profile
  profiles:
    active: local
        
